### ISSUE TITLE
Can't use hostnames in pillar

### ISSUE THREAD

**Issue by bogdanr** [tcpcloud/salt-formula-glusterfs#3]
Having this in pillar works just fine:

```
glusterfs:
  server:
    peers:
    - 172.31.63.120
    - 172.31.55.151
```

This doesn't work:

```
glusterfs:
  server:
    peers:
    - server1
    - server2
```

In the second case it errors out something like this:

```
server1:                                                                                                                                                                                                                                                                  
----------                                                                                                                                                                                                                                                                        
          ID: glusterfs_peers
    Function: glusterfs.peered
        Name: server2
      Result: False
     Comment: peer probe: failed: Probe returned with unknown errno 107
     Started: 19:04:44.194818
    Duration: 236.696 ms
     Changes:   
----------
```

If I manually write the state like this it also works:

```
glusterfs_peers:
    glusterfs.peered:
      - names: ['server1', 'server2']
```

but with `- names: {{ server.peers }}` it doesn't when using hostnames instead of IP addresses.
